my_string=input("Введите пожалуйста строку: ")
print(len(my_string))
print("Данная строка в высоком регистре: ",my_string.upper())
print("Данная строка в нижнем регистре: ",my_string.lower())
print("Данная строка без пробелов: ",my_string.replace(" ",""))
print("Первый символ строки: ",my_string[0])
print("Последний символ строки: ",my_string[-1])